# Generated by Django 6.0.5 on 2026-05-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Satuan',
                'verbose_name_plural': 'Satuan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('stok_minimal', models.PositiveIntegerField(default=0, help_text='Batas minimum stok sebelum sistem merekomendasikan pemesanan ulang')),
                ('stok_saat_ini', models.IntegerField(default=0)),
                ('tanggal_kadaluarsa', models.DateField(blank=True, help_text='Kosongkan jika tidak memiliki tanggal kadaluarsa', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barang_set', to='inventory.kategori')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barang_set', to='inventory.satuan')),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
                'ordering': ['nama'],
            },
        ),
    ]
