# Generated by Django 6.0.5 on 2026-05-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='tanggal_kadaluarsa',
        ),
    ]
