# Generated by Django 6.0.5 on 2026-05-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('alasan', models.CharField(choices=[('pemakaian_dapur', 'Pemakaian Dapur'), ('rusak', 'Rusak / Tidak Layak'), ('kadaluarsa', 'Kadaluarsa'), ('lainnya', 'Lainnya')], default='pemakaian_dapur', max_length=20)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keluar_set', to='inventory.barang')),
            ],
            options={
                'verbose_name': 'Barang Keluar',
                'verbose_name_plural': 'Barang Keluar',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masuk_set', to='inventory.barang')),
            ],
            options={
                'verbose_name': 'Barang Masuk',
                'verbose_name_plural': 'Barang Masuk',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
