# Generated by Django 6.0.5 on 2026-05-23 11:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_barang_tanggal_kadaluarsa'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangmasuk',
            name='tanggal_kadaluarsa',
            field=models.DateField(blank=True, help_text='Kosongkan jika tidak memiliki tanggal kadaluarsa', null=True),
        ),
        migrations.CreateModel(
            name='StokBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_awal', models.PositiveIntegerField()),
                ('jumlah_sekarang', models.PositiveIntegerField()),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.barang')),
                ('barang_masuk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='transactions.barangmasuk')),
            ],
            options={
                'verbose_name': 'Stok Batch',
                'verbose_name_plural': 'Stok Batch',
                'ordering': ['tanggal_kadaluarsa', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarangKeluarBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('barang_keluar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keluar_batches', to='transactions.barangkeluar')),
                ('stok_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keluar_batches', to='transactions.stokbatch')),
            ],
            options={
                'verbose_name': 'Barang Keluar Batch',
                'verbose_name_plural': 'Barang Keluar Batch',
            },
        ),
    ]
